Repository MissouriMRR/compakt, pull requests merged in 2024-10, with the labels that each got.

#50 Added Officer Signature Section to Logs
  package-lock.json
  package.json
  src/lib/structs.ts
  src/routes/logs/+page.svelte
  src/routes/record/+page.svelte
  svelte.config.js
Labels: enhancement, backend

#54 Changed Element Scaling Across Devices
  src/routes/+layout.svelte
  src/routes/logs/+page.svelte
Labels: bug, frontend

#56 Fixed button spillout
  src/routes/record/+page.svelte
Labels: bug, frontend

#57 Adjusted pop-up checklist scaling
  src/routes/+layout.svelte
Labels: bug, frontend

#58 More changes to checklist
  src/routes/+layout.svelte
Labels: bug, frontend

#51 Make the logos spin
  src/routes/+layout.svelte
  src/routes/+page.svelte
  static/favicon_blurred.png
  static/multirotorlogo_icon.png
  static/multirotorlogo_icon_blurred.png
  static/multirotorlogo_text.png
Labels: enhancement, frontend

#59 Fixed Signature Duplication Issue.
  src/routes/+layout.svelte
  src/routes/logs/+page.svelte
Labels: bug, frontend
