Repository MissouriMRR/compakt, pull requests merged in 2024-04, with the labels that each got.

#38 Added Missing Props
  src/lib/load.ts
  src/lib/stores.ts
  src/lib/structs.ts
  src/routes/+layout.svelte
  src/routes/api/logs/+server.ts
  src/routes/logs/+page.svelte
  src/routes/record/+page.svelte
Labels: bug, frontend, backend

#40 Feature/backend
  src/app.d.ts
  src/routes/api/logs/+server.ts
  src/routes/logs/+page.svelte
  src/routes/record/+page.svelte
Labels: backend

#41 Feature/frontend
  src/routes/+page.svelte
Labels: frontend

#47 Feature/frontend
  src/routes/record/+page.svelte
Labels: enhancement, frontend

#49 Feature/backend
  src/lib/data.ts
  src/routes/logs/+page.svelte
Labels: bug, backend
